server:
  port: "3000"
  base_url: /v1

database.master:
  name: master
  driver: mysql
  host: "localhost"
  port: 3306
  username: root
  password: 
  database: test
  debug: true

database.wamobi:
  name: wamobi
  driver: mysql
  host: "localhost"
  port: 3306
  username: root
  password: 
  database: test
  debug: true

auth:
  dash_api_key: admin
  jwt_key: c0br4d1g1t4L
  jwt_lifetime: 2880 # in minutes
  jwt_audience: Cobra Middleware
  jwt_issuer: Cobra Security Authority
  client_secret: c0br4d1g1t4L
